import dynamic from "next/dynamic";
import Head from "next/head";
import About_us from "../../components/About_us/About_us";
import { Button , Spacer , Fade ,  Link , Grid} from "@nextui-org/react";
import { Container } from "@mui/material"
import Posters from "../../public/posters/float.png";
import Image from "next/image";
// import './events.css'




const AnimatedCursor = dynamic(() => import('react-animated-cursor'), {
    ssr: false
});

export default function Events() {
    return (
        <div className="body">
            <AnimatedCursor
                innerSize={15}
                outerSize={40}
                color='255, 255, 255'
                outerAlpha={0.2}
                innerScale={0.6}
                outerScale={2}
                trailingSpeed={3}
            />
            <Head>
                <title>Float-a-RIG</title>
            
            </Head>
            
            <div className="about" id="about">
            {/* <h1 className="about-header">Float-a-RIG</h1> */}
            <Container className="abt-cont">
                <Grid.Container gap={2} justify="center" className="about-content">
                    <Grid xs={12} md={6} className="flex flex-col abt-text-section">
                            {/* <p className="about-main-text">All Work, All Play</p> */}
                            {/* <p className="about-subtext">I&apos;m a Computer Science Undergraduate and a Frontend Developer from India 🇮🇳 Student at heart, and a Developer by profession, I make frontends look good with JavaScript and a sprinkle of CSS ✨ </p> */}
                            <p className = "about-subtext">
                                {/* <span shadow color = "gradient" className="gradient-text">Symbiosis Institute of technology </span> */}
                                Participants have to bulid a model floating platform for deep sea wind farms which withstands turbulent currents, high-speed winds and tides while the mounted turbines rotate.
<br/>A model of a floating wind turbine will be tested with a wind machine. An LED should light up to show power generation.

.<br/></p>  
<h1 className="about-main-text">Event Rules</h1>
 {/* Everyone regardless of their branch will come together to showcase the perfect two days.  */}

{/* <span shadow color = "gradient" className="gradient-text">SymbITech</span>  */}
{/* will help young minds, broaden their vision, and surrender to their instincts for knowledge */}
  

<br/>
<p className="about-subtext">
1. Models should be able to float with the wind machine on.<br/>
2. Mini turbines of standard size will be made beforehand using the laser cutting machine and 3D printer.<br/>
3. Participants may submit a custom turbine model based on given schematics to be printed and laser cut, at least a week before the event. The turbines will be given to them during the fest.<br/>
4. On Day 1, static testing will be conducted for the prototypes. Teams can then update their models for the final wind testing on Day 2.<br/>
5. Teams must use wind turbines to generate enough power to light up a small LED.<br/><br/>

<b>Materials Provided:</b> U Hooks, D Rings, 2mm steel wire spools, Plier, Wire Cutter, Nylon Cording/Wire, Popsicle Sticks, QuickDry Glue, Balloons, Straws, Jumper Wires, Breadboard, Mini LEDs, Mini Alternators/Generators.<br/><br/>
<b>Team Size: </b> Group of 4
<br/><br/>
<b>Judging criteria:</b>
1. Points for light weight model that floats with the weight of turbines. <br/>
2. Bonus points for working LEDs using the power generated by the turbines. <br/>
3. Points for speed and efficiency of assembly.<br/>



</p>                            
                            <p className="about-subtext"></p>
                            <Spacer y={1} />
                            <Button  className="about-btn" size="xlarge" shadow color="gradient" auto>
                            <Link href = "/register">Register Now</Link>
                            </Button>
                        

                    </Grid>
                    <Grid xs={12} md={6} justify = "center" className="about-img-col">
                        
                            <Image className="about-img" src={Posters} bottom="400px"/>
                        
                    </Grid>
                </Grid.Container>
            </Container>
        </div>
        </div>
    )
}